config/routes.rb
Vikings::Application.routes.draw do

  get "/culture", to: "static_pages#culture"
  get "/gods", to: "static_pages#gods"
  get "/game_rules", to: "static_pages#game_rules"
  get "/timeline", to: "static_pages#timeline"
  get "/map", to: "static_pages#map"
  get "/strategic_map", to: "static_pages#strategic_map"
  get "/hideout", to: "static_pages#hideout"
  get "/homerules", to: "static_pages#homerules"
  root "static_pages#home"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def gods
  end

  def game_rules
  end

  def map
  end

  def strategic_map
  end

  def hideout
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted">
    Forgotten Horrors Dungeons and Dragons
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55905413-1', 'auto');
  ga('send', 'pageview');

</script>
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Forgotten Horrors", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Gods", gods_path %></li>
        <li><%= link_to "Rules", game_rules_path %></li>
        <li><%= link_to "Hideout", hideout_path %></li>
        <li><%= link_to "Zoom Map", map_path %></li>
        <li><%= link_to "Strategic Map", strategic_map_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forgotten Horrors</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/header'%>
<div class="container">
<%= yield %>
</div>
<%= render '/layouts/footer'%>
</body>
</html>

app/views/static_pages/culture.html.erb
<div class="center">
  <%= image_tag("culture.jpg") =%>
</div>
<h1>Kultuur</h1>

<p>
Skandinaavialased on väga lärmakas, uhke, jäärapäine ja religioosne rahvas. Nad austavad jõudu, ausust ning endast targemaid. Nad põlastavad pettureid, nõrku ning reetureid.
</p>

<p>
Oma päevi veedavad nad tööd tehes ning treenides, pidevalt harjutades võitlemist. Õhtuid veedavad nad pidutsedes ja juues. Kui Skandinaavialastel omavahel tüli tekib, siis tihti lahendatakse küsimus jõudu kasutades. Rikkamatel viikingitel on oma talu ja maa. Vaesemad töötavad tihti sõdurite, valvuritena, sulastena või pühakodades. Suuremates auküsimustes kutsutakse üksteist välja duellile, mis tihti lõppeb ühe poole surmaga. Enamuse lihttöid teevad nende eest ära ohtrates kogustes orjad, mis on toodud idast. Kehtivad eri seadused Skandinaavialastele ning orjadele - orjadel põhimõtteliselt puuduvad igasugused õigused. Nende isand võib teha nendega mis iganes talle meeldib. Kuid see ei tähenda, et orje koheldaks väga halvasti. Aeg-ajalt mõni isand vabastab mõne orja, kuid endine ori töötab tihtipeale sama isanda juures vabatahtlikult edasi, lihtsalt ausa tasu eest.
</p>

<div class="center">
  <%= image_tag("woman_warrior.jpg") =%>
</div>

<p>
Skandinaavia rahvas on üks vähestest rahvastest maailmas, kus mehed ja naised on võrdsed. Skandinaavia naised võivad olla täpselt samamoodi Jarlid või valitsejad, ning tihtipeale ongi, ning keegi ei vaata sellele halvasti. Peredes on mehed ja naised võrdsel kohal. Naised harjutavad samamoodi võitluskunsti, nagu mehed ning peresisesed tülid lahendatakse täpselt samamoodi kakeldes, küll aga lõppevad need kaklused harvem teine-teise surmaga. Naisi võetakse ka reidimistele kaasa. Tõsi ta on - tihti on viikingid näinud vaenlasi hirmust tardumas, kui nad näevad nende poole jooksmas nais sõdurit. Kõige hirmuäratavamad on vaenlastele Valküürid - surmatoojad. Nende nägemise peale jookseb tihtilugu vastaspoole vägi koheselt igas suunas laiali.
</p>

<div class="center">
  <%= image_tag("valkyre.jpg") =%>
</div>

<p>
Kõige rohkem hirmutab vaenlasi viikingite juures tõsiasi, et nad ei karda surma. Viikingid taganevad, kui nad näevad, et lahingul ei ole mõtet, kuid nende silmis ei näe kunagi hirmu. Kõik viikingid tahavad surra lahingus. See on tee ja värav valhallasse - Skandinaavia jumalate taevasse. Need, kes surevad vanadusse, need ei saa valhalasse. Tihtipeale paluvad vanad mehed põlvili Jarlilt, et ta võtaks ta reidile kaasa, lihtsalt selleks, et tal oleks ka võimalus lahingus surra.
</p>

<p>
Viikingid on külmaverelised tapjad, kes ei näe midagi valesti selles, et nad teise tapavad. Kui vaenlane langetab relva paanikas, siis viiking võtab seda nõrkuse märgina, põlastab seda ja üldjuhul tapab ta kohapeal. Mõni õnnelik võetakse ka vangi ja eluaegseks orjaks.
</p>

<div class="center">
  <%= image_tag("old_man.jpg") =%>
</div>

app/views/static_pages/game_rules.html.erb
<div class="center">
  <%= image_tag("game_rules.jpg") =%>
</div>

<h1>Game rules</h1>

<p>
Game system 5e, any aligment, any race, any class, level 1<br/>
Starting equipment background and class only. No gold buy<br/>
Background can be custom, but must be discussed with DM first<br/>
<br/>
Point buy 27, max stat 15, standard. Special flavor traits apply for low ability score:

<ul>
<li>Str 8 - weak beyond measure - A wimp</li>
<li>Dex 8 - walking disaster - clumsy as fuck</li>
<li>Con 8 - frail body - catches every bad thing there is</li>
<li>Int 8 - dimwit - stupid, stupid, stupid</li>
<li>Wis 8 - reckless - doesnt think stuff through</li>
<li>Cha 8 - ugly - Ugly</li>
</ul>
<br/>

Traits for flaw - You can think of 1 trait and 1 flaw besides background stuff. They must be discussed with DM first. The flaw must be a relevant flaw and the stronger the trait, the stronger the flaw. <br/>
Trait - Blind monk - No usual penalties while fighting againt invisible creature.<br/>
Flaw - Blind - well im blind.<br/>
<br/>

PVP is OK if it is for reasonable RP reasons(Cleric of pure good sees his party member is raising zombies/a party member is constantly fucking with others and completely undermining party effors. In addition, he refuses to leave the party). Bullshit RP reasons are not ok(He took the best loot item, my character would obviously kill him and take it to himself/My character hates elves, so i attack him the moment i see him).
<br/><br/>

Lucky feat does not give disadvantage super advantage. (what was wotc thinking)<br/>

Drinking a potion or applying poison is an interaction<br/>

Drwaing 2 weapons is an interaction, if you have 2 free hands<br/>

Switching weapons is a bonus action<br/>

Dropping a shield is interaction. Strapping a shield is an action. Putting shield on the back is an action.<br/>

Inspiration does not carry over to the next game<br/>

Resurrection spell components with cost are 10x more expensive<br/>

Long rest is inteerupted if combat happens which causes more than 60% of party to lose more than 10% max hp each or single member to lose more than 60% max hp<br/>

Great weapon master and sharpshooter lose -5/+10 and gain +1 str/dex respectively.<br/>

<br/>
DISARM <br/>
A creature can use a weapon attack to knock a weapon or another item from a target's grasp. The attacker makes an attack roll contested by the target's Strength (Athletics) check or Dexterity (Acrobatics) check. If the attacker wins the contest, the attack causes no damage or other ill effect, but the defender drops the item. The attacker can choose a location in 15 foot radius where the item drops.<br/>
The attacker has disadvantage on its attack roll if the target is holding the item with two or more hands or if he doesnt have a weapon of his own(unless he has Martial arts or unarmed feat).<br/>
The target has advantage on its ability check if it is larger than the attacking creature, or disadvantage if it is smaller.<br/>
<br/>
TAKE WEAPON OR ITEM<br/>
A creature can use a weapon attack to take a weapon or another item from a target's grasp. The attacker makes an attack roll contested by the target's Strength (Athletics) check or Dexterity (Acrobatics) check. The attacker has disadvantage on its attack roll and needs a free hand to take the item. If the attacker wins the contest, the attack causes no damage or other ill effect, but takes away the item of defender.<br/>
The target has advantage on its ability check if it is larger than the attacking creature, or disadvantage if it is smaller.<br/>
</p>
<p>
<h2>Background info:</h2>
You start in a city-state called Nurdhun. It is a very religious big coastal city with a population of over 20000 and roads comming from 3 sides. Nurdhun is a properous city where most of the people follow Kjellism. It has the most powerful army in the region and in times of war can wield more than 2000 troops.
</p>
<p>
However, complex times have befallen upon Nurhun. The desert wars in the north of the Nurdhun have forced thousands of refugees to take refugee in Nurdhun. While Nurdhun does its best to accept and help the refugees, due to its well-known and generous major Frank, a lot of religious issues have risen. In the northen deserts, the people follow the god Madite. Madites and Kjellismes have never gotten along well. Hate crimes, kidnappings, robbing and even murders are abound. The major Frank does his best to calm the situation, with his religios advisor Joosep known for breaching the excommunication of refugees and his military advisor Mike known to ignore any hate crimes that happen against Madites, his hands are pretty tied. To make matters worse, a neighbouring city-state, the Gruthan has vowed to declear war, should the Madites ever be seriously threatened in the city of Nurdhun.
</p>
<p>
The players are citizens of Nurdhun. The need to think for at least 1 very strong emotional bond inside the city and they have spent inside the city a minimum of 1 year, if not more(maybe even entire life?). By now, the players are citizens of Nurdhun, one way or another. If the player is not a follower of Kjellism, then he needs to think of a way he fooled the officials to believe that he was one. The players need to think how did they make their living there and why did they spend so much time in there.
</p>
<p>
The city of Nurdhun, highly religious as it is, hold a ritual every year. The day of the ritual is coming, where all the people of Nurdhun will gather around the main square in the town. Each and every citizen appears to the ritual with a mask. Then a small cookie is given to each of them. The gods choose who gets what kind of cookie, but everybody goes home and when they open the cookie, they see if they are the chosen ones by Kjell himself. If they are, they will know how to meet the other chosen ones and are bound to be the protectors of the Nurdhun, called Nurdhans. Their identities remain secret from the other people of the realm. It is their duty, to ensure the Nurdhun prospers and is a just city. When they go public while wearing their masks, then everybody will know that they are dealing with the protector of Nurdhun and nobody has the authority to ask them to remove it. Nurdhans take great pride in their masks and usually make sure that they are elaborate and decorative, but they only wear them when they want their identities to remain secret.
</p>

app/views/static_pages/gods.html.erb
<div class="center">
  <%= image_tag("seer.jpg") =%>
</div>
<h1>Wold and Religion</h1>

<p>
The Selvarin is an ancient world, having suffered numerous wars that have been so devastating that all life was almost extinguised multiple times.
</p>

<p>
Religion is held in very high regard in Selvarin. Rarely are there any people who dont believe in god and with good reason - they undoubtedly exist. After the great war between gods, devils, dragons, demons, giants, monsters and men, called Ragnarok, most of the gods were dead. From the ashes of ancient civilization, a few gods raised to rebuild this broken and forsaken world.
</p>

<p>
<h2>Kjell</h2>
Kjell was once a normal human, raised to godhood in Ragnarok. His morals are simple and reasonable. They can be summarised with "Dont fuck with each other but dont let anybody fuck you either"(You can still have sex and lots of it). Men and women are equal in Kjells eyes and so are they in the regions that follow Kjell. Large regions in Selvarin follow Kjell.
</p>

<p>
<h2>Madite</h2>
Madite is an ancient god of Selvarin who was, for all intents and purposes, overthrown by Kjell. The Madites often hate the Kjellismes and the opposite is also true. The Madite is a very strict god and has become more and more draconian as the time has moved forward. In the large areas where Madite is the main god, its often illegal to follow other gods, or at least hard. The Madite law is dominant in there. In Madite law the women are often subjucated and need to wear heavy clothing to cover themselves up and masks called Mads that cover their face. The men need to shave every inch of hair they have on their body, heavy clothings and follow rigorous religios ceremonies multiple times a day.
</p>

<p>
<h2>Zedon</h2>
Zedon is a late god that started reaching godhood quite recently. The people of Zedon are the most peaceful and liberal of the three gods. They got tired of the constant hate between Kjellisms and Madites and believe everybody in the world are equal. They see the life as being a constant suffering and by being good and kind to others you reach absolution. Zedons are often harrased by the followers of other religion, as the others see them as pussyes.
</p>

app/views/static_pages/hideout.html.erb
<div class="center">
  <%= image_tag("crew.jpg") =%>
</div>

<h1>Contributing</h1>
<p>

<a href="https://bitbucket.org/stenver/forgotten_horrors">The Repository is here</a>
<br/>
<a href="https://bitbucket.org/stenver/forgotten_horrors/src/fa711aaa39041fe9c75b943fa24541aa449e3bdb/app/views/static_pages/home.html.erb?at=master&fileviewer=file-view-default"> The most important file is home.html.erb</a>

<br/>
<a href="https://bitbucket.org/stenver/forgotten_horrors/src/fa711aaa39041fe9c75b943fa24541aa449e3bdb/app/assets/images/?at=master">The images are here</a>

<br/>
To install:<br/>
<code>
  git pull<br/>
  cd forgotten_horrors<br/>
  bundle<br/>
  rails s<br/>
</code>
It should not run on <a href="http://localhost:3000/">localhost:3000</a>

</p>

<p>
Loot <a href="https://docs.google.com/spreadsheets/d/10ftFez0HpTSuZOMQqD-olR6J3vzM1EApSdYWNAgMNkM/edit#gid=78922621">HERE</a>
</p>

<div class="center">
  <%= image_tag("books_read.jpg") =%>
</div>

<h2>Tower of Heroes Guild</h2>
<p>
Top of the tower treasure: 21697 gold<br/>

A treasure room, holding 1 321 213 gold coins.<br/>

<h3>Crew:</h3> <br/>
Vola nola - pea arch mage<br/>
Gillmore Petyra - pea alkeemik<br/>
Ragnar - Pea kaitsja<br/>
Kuldotha - Pea smith<br/>
Rog - pea kaevur, br<br/>
Daleek - Bolgi ihukatsja, külaline<br/>
<br/>
<h3>SECRET ROOMS DISCVERED</h3>
Ground floor - Massiivne portaal millest saavad terved armeed läbi liikuda.<br/>
Raamatukogu library secret room - Lugemistuba 6 kohaga, kus advantage lugemisel ja bürokraatlikud raamatud.<br/>
Top of the tower - Zigurathi kristall olemas<br/>
Armory secret room - Kahjuks tühjaks kammitud.<br/>
Storage secret room - Another storage area, holding 4 teleportation portal crystals. These can be used to create additional portals(1 for small, 2 for medium, 4 for army).<br/>
Master office secret room - comfortable area with potion of speed, involunerability, 3x greater healing, 2x superior healing, 1x best healing.<br/>
Smithy secret room - Comfortable leisure area, has bracers, giving advantage for creating items.<br/>
Jail secret room - A magical jail with 3 of antimagic cells.<br/>
Control room - Holding 5 magical holding tubes, 3 broken, 2 working. Takes 2 to protect against scrying and 3 to protect against teleportation. Fuel rods - Dragon hearths<br/>
Treasure room - Holding massive amount of gold and full of anti-magic.<br/>
A huge room holding an airship, able to take to the skies. Needs a crew of 15 to operate. and 15 cannons on the side<br/>
</p>

<div class="center">
  <%= image_tag("airship.jpg") =%>
</div>

<h2>Crew</h2>
<p>
  <ul>
    <li>Lao'er - An old man who studies the long forgotten dead. Assigned to the GILFs party as nobody in the world knows as much about the dead as he does</li>
    <li>Erevan - an elven man of nature, that can turn himself into terrible beasts.</li>
    <li>Adindin - A stupid and reckless drow who looks weak as well. Blessed with with dragonic magic, however, showing hidden potential.</li>
    <li>Granny - An old dwarven lady who offers tea and cookies to everybody and whacks all the rude people with his rolling bin.</li>
    <li>Eero - A halfling with many faces and identities. Its hard to even know if Eero is his true name.</li>
    <li><strike>Sha-Il - A half elf warlock who is not afraid to kick someone in the face, should the worst happen. Sould sucked out by a banshee when running from the undead horde.</strike></li>
    <li><strike>Lia - An elven woman a faith, abondened by the GILFs and MIA on the dwarven smugglers island. Found by GILFs later in prison and freed by them. Killed by Franks skeletal horde when Frank revealed his true nature</strike></li>
    <li><strike>Meh - A human monk, dedicating his life for the good and kicking the nuts. Killed by the Dwarven captain on the heroes guild island.</strike></li>
    <li><strike>Geth - A naked guy with a greataxe who sees strange visions. Killed by black dragon on the heroes guild island.</strike></li>
    <li><strike>Some guy - we will never know what happened to him in the tower</strike></li>
  </ul>
</p>

app/views/static_pages/map.html.erb
<script>
function showPicture() {
  $("#selvarin").elevateZoom(
    {
      zoomType : "lens",
      lensShape : "round",
      lensSize : 800
    }
    );
  $("#loading-bar").hide();
  $("#picture-holder").show();
}
</script>
<div style="display:none">
  <img id="big-picture" src="/assets/selvarin.jpg" onload="showPicture()">
</div>
<div id="loading-bar">
  <div class="spinner"></div>
</div>
<div id="picture-holder" style="display:none">
  <%= image_tag("selvarin_thumb.jpg", id: "selvarin", data: {'zoom-image' => "/assets/selvarin.jpg"}) =%>
</div>
<p>
  <h1><a href="/assets/selvarin.jpg">FULL IMAGE<a></h1>
</p>

app/views/static_pages/strategic_map.html.erb
<div class="center">
  <%= image_tag("selvarin_strategic_47_allies.png") =%>
</div>